### ISSUE TITLE
wxIcon : Segfault in Delete()

### ISSUE THREAD

**Issue by GWRon** [maxmods/wx.mod#43]
I just had a segfault in my wxmax-application:
It contained code which was used before the wxIcon commit (allowing for icons from resources).

Segfault in `bmx_wxicon_delete(wxObjectPtr)` of the `Delete()` method in wxicon.bmx.

Code I am using in my app (`OnInit()`):
```blitzmax
Local icon:wxIcon = New wxIcon.Create()
icon.LoadFile("myicon.ico", wxBITMAP_TYPE_ICO)
If Not icon.IsOk() Then Throw("Can't load 'myicon.ico'")
SetIcon(icon)
```

Commenting it out will remove the segfault.

**Comment by GWRon** [comment]
I replaced my code with the one you posted in the issue  #40 👍 

```BlitzMax
frame.SetIcon(wxIcon.CreateFromResource("APP_ICON"))
```

and it segfaults the same way.

**Comment by woollybah** [comment]
So it turns out that I'd declared the function as `void*` rather than `void`, but the Extern was for void. This had an interesting effect, of calling the correct delete function, and *then* calling the subsequent function in the code, which happened to be `bmx_wxicon_copyfrombitmap()`, which obviously hadn't a clue what it was supposed to be doing, and fell over.

Interesting :-)
